package models;

// Generated Jul 4, 2015 5:56:59 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkedAccount generated by hbm2java
 */
@Entity
@Table(name = "linked_account")
public class LinkedAccount implements java.io.Serializable {

	private Integer id;
	private User user;
	private String providerUserId;
	private String providerKey;

	public LinkedAccount() {
	}

	public LinkedAccount(User user, String providerUserId, String providerKey) {
		this.user = user;
		this.providerUserId = providerUserId;
		this.providerKey = providerKey;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "provider_user_id")
	public String getProviderUserId() {
		return this.providerUserId;
	}

	public void setProviderUserId(String providerUserId) {
		this.providerUserId = providerUserId;
	}

	@Column(name = "provider_key")
	public String getProviderKey() {
		return this.providerKey;
	}

	public void setProviderKey(String providerKey) {
		this.providerKey = providerKey;
	}

}
