package models;

// Generated Jul 4, 2015 5:56:59 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import be.objectify.deadbolt.core.models.Permission;

/**
 * UserPermission generated by hbm2java
 */
@Entity
@Table(name = "user_permission")
public class UserPermission implements java.io.Serializable, Permission {

	private int id;
	private String value;
	private Set<User> users = new HashSet<User>(0);

	public UserPermission() {
	}

	public UserPermission(int id) {
		this.id = id;
	}

	public UserPermission(int id, String value, Set<User> users) {
		this.id = id;
		this.value = value;
		this.users = users;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_has_user_permission", joinColumns = { @JoinColumn(name = "user_permission_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
